#!/bin/bash
OPEN_JDK_JAR=/usr/lib/jvm/java-11-openjdk-11.0.7.10-1.fc32.x86_64/bin/jar
ORACLE_JDK_JAR=/usr/java/jdk-11.0.7/bin/jar

function benchmark() {
	INDEX_DIR=`mktemp -p /tmp -d index.XXXX`
	INDEX_FILE=$INDEX_DIR/index

	unzip -oq build/libs/*.jar -d $INDEX_DIR
	touch $INDEX_FILE

	printf "$INDEX_FILE generated by $1: "
  _TIME=$(time(
		for attempt in `seq 1 10`; do
			for jar_file in `find $INDEX_DIR -name *.jar`; do
				$2 $jar_file | awk '{ print $NF }' | grep .class$ > $INDEX_FILE
			done
		done
  ) 2>&1)
  TIME=`echo $_TIME | cut -d' ' -f2`
	TIME_SECONDS=`echo "$TIME" | awk '{split($0,m,"m");split(m[2],s,"s");print m[1]*60+s[1]}'`
	printf "$TIME_SECONDS""s"

	if [ -z "$BASE_TIME_SECONDS" ]; then
		BASE_TIME_SECONDS="$TIME_SECONDS"
		echo ""
	else
		awk -v x="$TIME_SECONDS" -v y="$BASE_TIME_SECONDS" 'BEGIN {print " (" x/y "x)"}'
	fi
}

benchmark "unzip" "unzip -l"
benchmark "jar (open jdk 11)" "$OPEN_JDK_JAR tf"
benchmark "jar (oracle jdk 11)" "$ORACLE_JDK_JAR tf"
